### ISSUE TITLE
Missing extra.wad

### ISSUE THREAD

**Issue by speedvoltage** [Hammermaps-DEV/Spirit-of-Half-Life-1.9--VC2010#1]
Hi,

I am not sure if it is an issue to do with me missing something or the file not being present with this installation, but maps tramtutor.bsp and weathdemo.bsp cannot be opened due to extra.wad being missing. Upon trying to load those maps, the mod will just crash with an error message.

Was the file forgotten or did I not look somewhere?

**Comment by hammermaps** [comment]
hello, I look at this, could be, because I have decomposed something.
