### ISSUE TITLE
Add viewroll and viewmodel bob tilt | Returns old bobbing from the WON/retail version | Addresses issue #1544 

### ISSUE THREAD

**Issue by hammermaps** [Hammermaps-DEV/Spirit-of-Half-Life-1.9--VC2010#3]
https://github.com/ValveSoftware/halflife/pull/2900

**Comment by barney-heatwave** [comment]
Nice to see that this may be added to another mod :D

**Comment by hammermaps** [comment]
Yes, this is optionally integrated in sol 1.9a.
For those who want it.

:)

**Comment by hammermaps** [comment]
https://github.com/Hammermaps-DEV/Spirit-of-Half-Life-1.9--VC2010/commit/2f7f97992470bef66c87f3b996cc3e8fc0d0bc36
